class createModule {
  var uid;
  var location;
  var pushKey;
  var phoneNumber;
  var token;
  var chatid;
  var latitude;
  var longitude;
  var date;
  var qty;
  var packageID;
  var note;
  var status;
  var price;
  var recLatitude;
  var recLongitude;
  var dLastName;
  var dFirstName;
  var dPhone;
  var senderPhone;
  var driverUID;
  var ABACode;
  var assignBy;
  var senderFname;
  var senderLname;
  var senderName;

  // createModule(
  //   this.uid,
  //   this.location,
  //   this.pushKey,
  //   this.phoneNumber,
  //   this.token,
  //   this.chatid,
  //   this.latitude,
  //   this.longitude,
  //   this.date,
  //   this.qty,
  //   this.packageID,
  //   this.note,
  //   this.status,
  //   this.price,
  //   this.recLatitude,
  //   this.recLongitude,
  //   this.dLastName,
  //   this.dFirstName,
  //   this.dPhone,
  //   this.senderPhone,
  //   this.driverUID,
  //   this.ABACode,
  //   this.assignBy,
  //   this.senderFname,
  //   this.senderLname,
  //   this.senderName,
  // );
}
